### ISSUE TITLE
日付別勤怠情報取得

### ISSUE THREAD

**Issue by nanakoasakawa** [nanakoasakawa/atte#10]

**Comment by nanakoasakawa** [comment]
トップ画面に当日の勤怠を表示する

**Comment by nanakoasakawa** [comment]
日付を選択して過去の勤怠を表示させる

**Comment by nanakoasakawa** [comment]
データの作成（シーディング）

**Comment by nanakoasakawa** [comment]
データを表示させる

**Comment by nanakoasakawa** [comment]
ちゃんとしたデータを表示させる

**Comment by nanakoasakawa** [comment]
日付別の勤怠を表示させる方法、休憩時間および勤務時間の計算方法がわからず途中

**Comment by nanakoasakawa** [comment]
Undefined property: Illuminate\Database\Eloquent\Relations\HasMany::$start
とのエラーが発生
$startが定義されていない？ようですが、どこで定義すればよいかわかりません。

**Comment by gem-yours** [comment]
`$this->hasMany('App\Models\Rest)->start`と書いて発生している状態でしょうか？
hasManyは1対nの関係になっているので、戻り値はRestではなく、n個のRestを束ねたオブジェクトになっています。
[参考記事](https://qiita.com/gone0021/items/084fbdec3b04ac1270f3#hasmany%E3%83%A1%E3%82%BD%E3%83%83%E3%83%89)のようにforeachを使うか、`$this->hasMany('App\Models\Rest)->first()->start`のように一番目の値を取り出す必要があります。

**Comment by nanakoasakawa** [comment]
Attempt to read property "start" on null (View: C:\xampp\htdocs\atte\attepj\resources\views\date.blade.php)
修正すると上記のようなエラーがでたのですが、これはDB上にデータがないという意味でしょうか。それとも、viewに定義されていないという意味でしょうか。

**Comment by gem-yours** [comment]
おそらくHasManyでデータを取得できていないのだと思います。`$this->hasMany('App\Models\Rest)->first()`だけで表示できるか試してみて下さい。

**Comment by nanakoasakawa** [comment]
$this->hasMany('App\Models\Rest)で表示させると、restsのデータを取得したいのにtimesのデータを取得しているようなので
修正方法を試してみましたができませんでした。どうすればよいかわかりません。

**Comment by gem-yours** [comment]
`getrest`の戻り値に問題がありますね。
https://github.com/nanakoasakawa/atte/blob/43332a1dce109c61d6da865a11395d01bb8262be/attepj/app/Models/Time.php#L36-L41

`$this`は自分自身を返すので、timesのデータを返してしまいます。
下のように取得したrestsを返すようにしてあげればデータが取得できていることが確認できると思います。
``` php
    return $this->hasMany('App\Models\Rest')->first();
```

**Comment by gem-yours** [comment]
# 日付別勤怠の表示
- [x] 当日の値を表示させる
- [x] whereで日付による検索を行う
- [x] 日付を入力するフォームを作成する
- [x] ルーティングでpostリクエストを受け付けられるようにする
- [x]  ページネーション

**Comment by nanakoasakawa** [comment]
勤務時間を表示させたいのですが、エラーが表示されます。
`public function gettime()
    {
        //勤務時間を計算する
        $timestart = new Carbon($this->start);
        $timeend = new Carbon($this->end);
        $time = $timestart -> diffInMinutes($timeend);
        $start = new Carbon($this->hasMany('App\Models\Rest')->first()->start);
        $end = new Carbon($this->hasMany('App\Models\Rest')->first()->end);
        $rest = $start -> diffInMinutes($end);
        $kintai = $time ->diffInMinutes($rest);
        return $kintai;

    }`
$kintaiがなぜ計算されないのかわかりません。

**Comment by gem-yours** [comment]
`diffInMinutes`の戻り値はCarbon（≒日付型）ではなくInt（整数型）になっています。
そのため、timeとrestの差分を求めるには`$kintai = $time - $rest;`で大丈夫です。

**Comment by nanakoasakawa** [comment]
モデルtime.phpとルーティングにweb.phpに追加したのですが、日付別のデータ取得がうまくできません。。

**Comment by nanakoasakawa** [comment]
当日の値を表示したいので、
date.blade.phpに
`<th><input type="date", name="kitanidate", value=**Carbon::today()**,min="2021-01-01",max="2026-01-01",value={{ $date }}>`
と記載したのですが、yyyy.mm.ddと表示されてしまいます。どうすればよいでしょうか。
