### ISSUE TITLE
会員登録/ログイン/ログアウト

### ISSUE THREAD

**Issue by nanakoasakawa** [nanakoasakawa/atte#5]

**Comment by nanakoasakawa** [comment]
laravel uiをインストールしてログイン機能を実装してみたのですが、どういう状況なのか理解できていません。
/registerは上書きされてしまったのでしょうか。

**Comment by gem-yours** [comment]
> /registerは上書きされてしまったのでしょうか。

以前作成したregisterの画面が表示されず、laraveluiの登録画面が表示されている理由はweb.phpの以下の行です。
``` php
Auth::routes();
```
より詳しく動作について知りたい場合は[こちら](https://gn-office.pro/archives/534)を参考にしてみてください。
また、`php artisan route:list`と打つとurlとcontrollerの紐づけを見ることができます。


混乱している原因と関係があるかはわかりませんが、コミットするブランチが2-projectのままになっていますね。
コミットするブランチを間違えたときには`git cherry-pick`などを使って修正ができます。ただ、今回の演習とはあまり関係がない部分ですので、こちらで修正してしました。`git pull`をすると`5-register`というブランチができているのが確認できると思います。`git switch 5-register`で切り替えて作業をお願いします。

**Comment by nanakoasakawa** [comment]
Auth::routes([
    'register' => false,  // ユーザー登録用のルート。デフォルトは true
]);
でregisterページのみ制御

**Comment by nanakoasakawa** [comment]
ログイン画面がうまくいきません。シーディングファイルで登録した初期データでログインを試みたのですが、ログインできませんでした。

**Comment by gem-yours** [comment]
登録画面からユーザを作成して、そのデータをmysqlで確認すると以下のようになっています。
```
mysql > select * from user;
+----+-----------------+-------------------------+--------------------------------------------------------------+---------------------+---------------------+
| id | name            | email                   | password                                                     | created_at          | updated_at          |
+----+-----------------+-------------------------+--------------------------------------------------------------+---------------------+---------------------+
|  1 | 山本　勇哉      | i13yamamoto2y@gmail.com | $2y$10$EVrS/Piw8Clms4XW7nLXuuoplAW4ddttdFUtGE9pJZC/AxVNZkQVi | 2022-04-27 21:07:01 | 2022-04-27 21:07:01 |
+----+-----------------+-------------------------+--------------------------------------------------------------+---------------------+---------------------+
```

パスワードをDBに平文で保存することはセキュリティ上のリスクとなるため、パスワードは暗号化して保存するようになっています。
シーディングファイルのパスワードも暗号化して保存すればログインできるようになります。
細かくは[こちら](https://qiita.com/nekyo/items/c85c372c8e7dd72a189a)をご覧になってください。
