### ISSUE TITLE
勤務開始

### ISSUE THREAD

**Issue by nanakoasakawa** [nanakoasakawa/atte#6]

**Comment by nanakoasakawa** [comment]
勤務開始時間をボタン押下してDBに登録したく、
コントローラーとルーティングにstartaddを追加したのですが
この次に勤務開始時間をタイムスタンプ？で登録するにはどうすれば良いのかわかりません。

**Comment by gem-yours** [comment]
日付系のカラムを登録したいときにはCarbonを指定すれば自動で型に合わせてくれます。現在時刻を設定したいときには以下のようにCarbonインスタンスを渡してあげれば大丈夫です。
```
$param=[
    'date'=> new Carbon(),
    'start'=> new Carbon(),
```

**Comment by nanakoasakawa** [comment]
勤務開始時間ボタン押下して開始時間のみDBに登録したいのですが、下記のエラーが表示されます。endも追加しなければならないのでしょうか。
SQLSTATE[HY000]: General error: 1364 Field 'end' doesn't have a default value

**Comment by gem-yours** [comment]
その解釈で大丈夫です。
対応としては、マイグレーションファイルの方でendを`nullable`にして、登録の際にはnullを指定するというのがあります。

**Comment by nanakoasakawa** [comment]
endの登録の際にnullになるような設定にしてみましたが、そこが解決したのかわかりません。
その前に別の下記エラーが表示されてしまいました。user_idにも問題があるようでしたので、認証されたユーザーのユーザーIDで登録されるようにしたかったのですがエラーの解決方法がわかりません。
Access to undeclared static property Illuminate\Support\Facades\Auth::$user

**Comment by gem-yours** [comment]
おそらくendの方は大丈夫です。
認証されたユーザの取得については[こちら](https://qiita.com/ucan-lab/items/a7441bff64ff1f173c10)を参考に書き方を確認してみて下さい。
