### ISSUE TITLE
休憩開始

### ISSUE THREAD

**Issue by nanakoasakawa** [nanakoasakawa/atte#8]

**Comment by nanakoasakawa** [comment]
休憩開始時間の登録について、
外部キー（time_id）について、1対多の紐づけがうまくできません。
'time_id'=>Time::where('date',new Carbon('today'))
の部分にwhereHasを使ってみたのですが、エラーになりました。

**Comment by gem-yours** [comment]
休憩時間の登録は`DB::table('rests')->insert($param);`の部分で行われるので、`$param`を宣言している時点ではリレーションは存在していません。ですので`whereHas`を使用する必要はありません。
休憩を登録するときには紐づけたいTimeを取得し、そのidをtime_idに指定してリレーションを作るという操作を行う必要があります。
``` php
'time_id'=>Time::where('date',new Carbon('today'))->first()->id,
```
